run:
  timeout: 5m                     # give linters up to 5m to complete
  tests: true                     # also run linters on *_test.go

issues:
  exclude-rules:
    - linters:
        - typecheck
      path: ^example/ppocr/.*\.go$
      text: "main redeclared in this block"  # ignore multiple main() declaractions in ppocr directory

linters-settings:
  errcheck:
    ignore: ''  # workaround to bug #4743, fix to upgrade to v1.62.0+