
version: "2"

run:
  timeout: 5m                     # give linters up to 5m to complete
  tests: true                     # also run linters on *_test.go

linters:
  default: none
  enable:
    - govet
    - unused

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0